// Single source of truth for all 172 Lollapalooza 2026 artists
// sp = Spotify artist URL, am = Apple Music artist URL
window.ARTISTS = [
  {n:"5 Seconds of Summer",t:"major",g:"Pop",sp:"https://open.spotify.com/artist/5Rl15oVamLq7FbSb0NNBNy",am:"https://music.apple.com/us/artist/665240429"},
  {n:"54 Ultra",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/6X5L6rmyvrWWu60Gx6exiZ",am:"https://music.apple.com/us/artist/1521471420"},
  {n:"Ado",t:"major",g:"J-Pop",sp:"https://open.spotify.com/artist/6mEQK9m2mMbga5asBCOz7V",am:"https://music.apple.com/us/artist/1494063681"},
  {n:"Ad\u00e9la",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/2qanRMyA5bNuTvz1dK45OP",am:"https://music.apple.com/us/artist/1765924916"},
  {n:"Aespa",t:"major",g:"K-Pop",sp:"https://open.spotify.com/artist/6YVMFz59CuY7ngCxTxjpxE",am:"https://music.apple.com/us/artist/1539111843"},
  {n:"After",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/7KfMR05zRrWyhQimnYa8li",am:"https://music.apple.com/us/artist/1674262029"},
  {n:"Alison Wonderland",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/11gWrKBemHl8g4BGAZbud3",am:"https://music.apple.com/us/artist/640530563"},
  {n:"Amber Mark",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/3MdG05syQeRYPQmLOBZbY0",am:"https://music.apple.com/us/artist/1099249070"},
  {n:"Amble",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5ZC7GPz5h9zkEfjZBUDNzI",am:"https://music.apple.com/us/artist/1671435415"},
  {n:"The Army, the Navy",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/4MAnvDgzeM6bAVUVUbUeFI",am:"https://music.apple.com/us/artist/1649412353"},
  {n:"Asha Banks",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/2uDFxcjRQnf8mjFwfqieSw",am:"https://music.apple.com/us/artist/943493421"},
  {n:"Audrey Hobert",t:"major",g:"Indie",sp:"https://open.spotify.com/artist/4N0TAwz9vhnQtjCqS65aKS",am:"https://music.apple.com/us/artist/1812750994"},
  {n:"Avello",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/1ZR5GnPw0Jkb5M4hnBwzuZ",am:"https://music.apple.com/us/artist/476861072"},
  {n:"Ayybo",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/0YVquC9RaJLYFNmlJFzkTV",am:"https://music.apple.com/us/artist/1603701193"},
  {n:"Bad Nerves",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/0MmLgGkWNb5wRq0SnhJvQH",am:"https://music.apple.com/us/artist/1213806228"},
  {n:"Balu Brigada",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/3GZsDnFf0qi8HJlqBOiomf",am:"https://music.apple.com/us/artist/1171521321"},
  {n:"BBNOS",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/15MAnlEjbQPWNbkjOlMqHD",am:"https://music.apple.com/us/artist/1161580951"},
  {n:"Beabadoobee",t:"major",g:"Indie",sp:"https://open.spotify.com/artist/35l9BRT7MXmM8bv2WDQiyB",am:"https://music.apple.com/us/artist/1434820941"},
  {n:"Bella Kay",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/0g9vAlRPKahk0bGcoPFwrl",am:"https://music.apple.com/us/artist/1706434165"},
  {n:"Beno",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/search/Beno",am:"https://music.apple.com/us/search?term=Beno"},
  {n:"Between Friends",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/2HkSsS8O2U2gPhnCGVN5vn",am:"https://music.apple.com/us/artist/1437540157"},
  {n:"Bixby",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/2YJQ1oYPK4cOHyihV8YOPt",am:"https://music.apple.com/us/artist/1539703709"},
  {n:"Blood Orange",t:"major",g:"R&B",sp:"https://open.spotify.com/artist/6RZUqkomCmb8zCRqc9eznB",am:"https://music.apple.com/us/artist/350760978"},
  {n:"Boris Brejcha",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/1g0Knil2DuPjMKrqJnFoHi",am:"https://music.apple.com/us/artist/202970860"},
  {n:"Boys Noize",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/1rDQ4ENAmX5UGC6kYby4FH",am:"https://music.apple.com/us/artist/200444417"},
  {n:"Bradeazy",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/1dESZUZevzhd5dzq9ZsMLI",am:"https://music.apple.com/us/artist/1755746338"},
  {n:"Calder Allen",t:"undercard",g:"Country",sp:"https://open.spotify.com/artist/2DaYaODkDErSy9PrJIBaWl",am:"https://music.apple.com/us/artist/1608248970"},
  {n:"Cameron Whitcomb",t:"undercard",g:"Country",sp:"https://open.spotify.com/artist/6TQj5BFPRhOlanMPaYKNdB",am:"https://music.apple.com/us/artist/1542957700"},
  {n:"Case Oats",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5Ml0QbIoj7bneIUJDCoMx8",am:"https://music.apple.com/us/artist/1502701947"},
  {n:"Chace",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/5kPhAZL6iV8iDywUmIPC3g",am:"https://music.apple.com/us/artist/207633892"},
  {n:"Chalk",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/3qa9pv6B0dmiBVETLQOCpi",am:"https://music.apple.com/us/artist/1344522004"},
  {n:"Charli XCX",t:"headliner",g:"Pop",sp:"https://open.spotify.com/artist/25uiPmTg16RbhZWAqwLBy5",am:"https://music.apple.com/us/artist/336060830"},
  {n:"The Chainsmokers",t:"major",g:"EDM",sp:"https://open.spotify.com/artist/69GGBxA162lTqCwzJG5jLp",am:"https://music.apple.com/us/artist/580391756"},
  {n:"Chezile",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/1EmdfupUQDpXOcb4Nj2mBH",am:"https://music.apple.com/us/artist/1502584860"},
  {n:"Chicago Made",t:"undercard",g:"Various",sp:"https://open.spotify.com/search/Chicago%20Made",am:"https://music.apple.com/us/search?term=Chicago%20Made"},
  {n:"Chicago Youth Symphony Orchestra",t:"undercard",g:"Classical",sp:"https://open.spotify.com/artist/38F4eptEGZAvPhZEjWS46W",am:"https://music.apple.com/us/search?term=Chicago%20Youth%20Symphony%20Orchestra"},
  {n:"Claire Rosinkranz",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/20rtnsgfcYqnFP8D4FwVTu",am:"https://music.apple.com/us/artist/1483262366"},
  {n:"Clipse",t:"major",g:"Hip-Hop",sp:"https://open.spotify.com/artist/3SpMmwMBBrtMYsNDiKMXFb",am:"https://music.apple.com/us/artist/3545947"},
  {n:"CMAT",t:"undercard",g:"Folk",sp:"https://open.spotify.com/artist/3Ggh0TjZ2DjVElKbWaoJiE",am:"https://music.apple.com/us/artist/1506697965"},
  {n:"Cortis",t:"undercard",g:"K-Pop",sp:"https://open.spotify.com/artist/1ebt9HnXdyYA6KgLXr1n4P",am:"https://music.apple.com/us/artist/1831651635"},
  {n:"Cruz Beckham and the Breakers",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/3ZPOiGqgEbfNlKFFKxXVsD",am:"https://music.apple.com/us/artist/1182571263"},
  {n:"Day We Ran",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/6dtbK89qIT2XjIsCQHjTxS",am:"https://music.apple.com/us/artist/1672278782"},
  {n:"Destin Conrad",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/1XW2MxNwH5JOKUCuGTxaeG",am:"https://music.apple.com/us/artist/852999989"},
  {n:"Devault",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/0I4AXHWcepIYO1F9VKyTBX",am:"https://music.apple.com/us/artist/1068294292"},
  {n:"Die Spitz",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/0zfZmpHTu0MlkkNr5KHeXE",am:"https://music.apple.com/us/artist/1545875931"},
  {n:"Disco Lines",t:"major",g:"EDM",sp:"https://open.spotify.com/artist/0YBbSFrj3ScOkMUoGsLNnh",am:"https://music.apple.com/us/artist/1462793893"},
  {n:"DJ Trixie Mattel",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/5RHEjxzUmYBLIYMpHLRhUC",am:"https://music.apple.com/us/artist/960467089"},
  {n:"Dombresky",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2xaRBZ2YXoKRBPAMlhz4gx",am:"https://music.apple.com/us/artist/1059827102"},
  {n:"Duke Dumont",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/5D1j3T3GjKI9iPvV10M2lN",am:"https://music.apple.com/us/artist/257148267"},
  {n:"Easy Honey",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5fKAYiCIzDsV8OqQDl8Erj",am:"https://music.apple.com/us/artist/1371966562"},
  {n:"Ecca Vandal",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/2ZaDPsylNEXAJwFaOIVxYB",am:"https://music.apple.com/us/artist/878909173"},
  {n:"Eli Brown",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/2S8tJoTWoajdKjpQFHwi7g",am:"https://music.apple.com/us/artist/1453200399"},
  {n:"Ella Boh",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/3UWNE3idxa2v2TMzrBRX11",am:"https://music.apple.com/us/artist/1377378873"},
  {n:"Ella Red",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/1hH4ajSTZKIBhwRymnZi5R",am:"https://music.apple.com/us/artist/1625139628"},
  {n:"Elizabeth Nichols",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/06cAJQBSPkt3bG7uMoWfmA",am:"https://music.apple.com/us/artist/1781318321"},
  {n:"EMI Grace",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/0U6MHJ9KRB5A1M7iHN06sS",am:"https://music.apple.com/us/artist/1510905623"},
  {n:"Empire of the Sun",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/67hb7towEyKvt5Z8Bx306c",am:"https://music.apple.com/us/artist/275254780"},
  {n:"Ethel Cain",t:"major",g:"Alt Pop",sp:"https://open.spotify.com/artist/6OJjKMcoHHPFGX8KiHzJkm",am:"https://music.apple.com/us/artist/1480663449"},
  {n:"Evening Elephants",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/4mvJqW3HQswIu7RmvcAQUy",am:"https://music.apple.com/us/artist/1655904238"},
  {n:"Fakemink",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/0qc4BFxcwRFZfevTck4fOi",am:"https://music.apple.com/us/artist/1744500063"},
  {n:"Faouzia",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/2w9zwq3AktTeYYMuhMjju8",am:"https://music.apple.com/us/artist/414067643"},
  {n:"Finn Wolfhard",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/2nmWcAqQtfgNp8Kpixa2CG",am:"https://music.apple.com/us/artist/1275324142"},
  {n:"Freddie Gibbs",t:"major",g:"Hip-Hop",sp:"https://open.spotify.com/artist/5gznATMVO85ZcLTkE9ULU7",am:"https://music.apple.com/us/artist/291049623"},
  {n:"Frost Children",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2m56hLeijJnEIYkjNMcYsT",am:"https://music.apple.com/us/artist/1505504789"},
  {n:"Geese",t:"major",g:"Rock",sp:"https://open.spotify.com/artist/6Qbmp6Si5ICaOjJYLBFOGS",am:"https://music.apple.com/us/artist/1378038472"},
  {n:"Goldie Boutilier",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/6W5dh1KhZhIkklWIlLhdKa",am:"https://music.apple.com/us/artist/1497564703"},
  {n:"Haute & Freddy",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/66T34XqGkEWbzKWALSBDuR",am:"https://music.apple.com/us/artist/1751891683"},
  {n:"High Vis",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/2Xx2fQvPpie3r2r4FYJdqz",am:"https://music.apple.com/us/artist/1479075772"},
  {n:"Horsegirl",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/2JeyedF7G0k3EVWkuPXUhP",am:"https://music.apple.com/us/artist/1482579399"},
  {n:"Hot Mulligan",t:"major",g:"Rock",sp:"https://open.spotify.com/artist/3JaAGmSTpnMcMManovd1BD",am:"https://music.apple.com/us/artist/941918833"},
  {n:"I-DLE",t:"major",g:"K-Pop",sp:"https://open.spotify.com/artist/2AfmfGFbe0A0WsTYm0SDTx",am:"https://music.apple.com/us/artist/1363570671"},
  {n:"INK",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/4ZhFCxPekpmV12n2xMeF2z",am:"https://music.apple.com/us/artist/695840203"},
  {n:"Inji",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/7bSkSMvm9gQmrXNjsZYS37",am:"https://music.apple.com/us/artist/1617715136"},
  {n:"IVRI",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5EjK7aUvQ9LMNqc2zXiWLS",am:"https://music.apple.com/us/artist/1349563025"},
  {n:"Jackie Hollander",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5ykY9Uweo3gl5VFpb6z6pQ",am:"https://music.apple.com/us/artist/1593254397"},
  {n:"Jade",t:"major",g:"Pop",sp:"https://open.spotify.com/artist/2WEWVhYGmKX2dCBDfTBoy8",am:"https://music.apple.com/us/artist/1753030541"},
  {n:"Jae Stephens",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/4HiLipaDjOwRkhJlk5s1uT",am:"https://music.apple.com/us/artist/796619154"},
  {n:"Jennie",t:"headliner",g:"K-Pop",sp:"https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M",am:"https://music.apple.com/us/artist/1414388378"},
  {n:"Jim Legxacy",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/7IrBqZo6diq3hV3GpUhrs2",am:"https://music.apple.com/us/artist/1460066773"},
  {n:"John Summit",t:"headliner",g:"EDM",sp:"https://open.spotify.com/artist/0PxzGnCYBpSuaI49OR94cA",am:"https://music.apple.com/us/artist/1494983226"},
  {n:"Julia Wolf",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/3wBwRixcsIrv9vqMSm8gNh",am:"https://music.apple.com/us/artist/1482698876"},
  {n:"Justine Skye",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/5HQVBKjBIaQroxNuh50aFq",am:"https://music.apple.com/us/artist/685830864"},
  {n:"Kettama",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/0XkX5uGPz5g0uf6qMgMgHN",am:"https://music.apple.com/us/artist/1425703970"},
  {n:"Khamari",t:"undercard",g:"R&B",sp:"https://open.spotify.com/artist/1tUoJwp2fGMBcnQfAPsGkq",am:"https://music.apple.com/us/artist/1042006565"},
  {n:"Kim Theory",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/search/Kim%20Theory",am:"https://music.apple.com/us/search?term=Kim%20Theory"},
  {n:"Kingfishr",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/6c2qQFq3xfxFJndX6wSe4f",am:"https://music.apple.com/us/artist/1616516476"},
  {n:"KLO",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2QlABGwVVmqOu8SHMyyZMq",am:"https://music.apple.com/us/artist/1528745657"},
  {n:"Know Good",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/4iogDJBJ2BO2jl8OkPrfpx",am:"https://music.apple.com/us/artist/1507153145"},
  {n:"KWN",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2KnhnL8zuqLhIhGk601fsb",am:"https://music.apple.com/us/artist/1629656232"},
  {n:"Leon Thomas",t:"major",g:"R&B",sp:"https://open.spotify.com/artist/3bPrBnSGrGpOiRh5eQsKgE",am:"https://music.apple.com/us/artist/267251475"},
  {n:"Lil Uzi Vert",t:"major",g:"Hip-Hop",sp:"https://open.spotify.com/artist/4O15NlyKLIASxsJ0PrXPfz",am:"https://music.apple.com/us/artist/1084228220"},
  {n:"Little Simz",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/6eXZu6O7nAUA5z6vLV8NKI",am:"https://music.apple.com/us/artist/569204972"},
  {n:"Loathe",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/7JEJzSD3D0hbdlWBLjjlsE",am:"https://music.apple.com/us/artist/377883434"},
  {n:"Lorde",t:"headliner",g:"Alt Pop",sp:"https://open.spotify.com/artist/163tK9Wjr9P9DmM0AVK7lm",am:"https://music.apple.com/us/artist/602767352"},
  {n:"Los Retros",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/1fafHhTXNmVEJFrLHgVFOT",am:"https://music.apple.com/us/artist/1045070073"},
  {n:"Love Spells",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5iiqhuffUTPEOjAUDj19IW",am:"https://music.apple.com/us/artist/1597025563"},
  {n:"Lucy Bedroque",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2I8H267eH5va9da4vGt38O",am:"https://music.apple.com/us/artist/1734729660"},
  {n:"Lyny",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/7xqIp1044Z2vd9v9ZphjLa",am:"https://music.apple.com/us/artist/1299141955"},
  {n:"Major Lazer",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/738wLrAtLtCtFOLvQBXOXp",am:"https://music.apple.com/us/artist/337765928"},
  {n:"Marlon Funaki",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/3BcSXip92N0HwJRA9sVmP6",am:"https://music.apple.com/us/artist/1513742282"},
  {n:"Max Styler",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/3NKKngINK1tP6BFy0WOyWk",am:"https://music.apple.com/us/artist/912353079"},
  {n:"MC4D",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/2MbY32LPINIi9P6PCkrOJI",am:"https://music.apple.com/us/artist/1278959109"},
  {n:"Momma",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/7vVERb8B2px2jM0FZ3Yfu7",am:"https://music.apple.com/us/artist/53773435"},
  {n:"Monaleo",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/5BVt6FBnKSAZGSnBPwMhEa",am:"https://music.apple.com/us/artist/1495603374"},
  {n:"Mother Mother",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/0e86yPdC41PGRkLp2Q1Bph",am:"https://music.apple.com/us/artist/269814858"},
  {n:"MPH",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/62SCu33InHVq97VaWw3eof",am:"https://music.apple.com/us/artist/465495678"},
  {n:"Muna",t:"major",g:"Indie",sp:"https://open.spotify.com/artist/6xdRb2GypJ7DqnWAI2mHGn",am:"https://music.apple.com/us/artist/1092611043"},
  {n:"Mustard",t:"major",g:"Hip-Hop",sp:"https://open.spotify.com/artist/0YinUQ50QDB7ZxSCLyQ40W",am:"https://music.apple.com/us/artist/316277873"},
  {n:"Nat Myers",t:"undercard",g:"Folk",sp:"https://open.spotify.com/artist/2QMlNryks9wyxBCsBGciTS",am:"https://music.apple.com/us/artist/1446778023"},
  {n:"The Neighbourhood",t:"major",g:"Indie",sp:"https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh",am:"https://music.apple.com/us/artist/594471569"},
  {n:"Nettspend",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/7ulIMfFr6vu8ME9yifk2oF",am:"https://music.apple.com/us/artist/1662047435"},
  {n:"New Constellations",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/5WF5jtgP0H31QTl5g4WxW9",am:"https://music.apple.com/us/artist/1543078051"},
  {n:"Next of Kin",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/668OF7yLpmsPIL10HHKPFC",am:"https://music.apple.com/us/search?term=Next%20of%20Kin"},
  {n:"Ninajirachi",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2FS0rOBzxF4ujGAnKXnHGO",am:"https://music.apple.com/us/artist/1210938233"},
  {n:"Not for Radio",t:"major",g:"Alt Pop",sp:"https://open.spotify.com/artist/2sKZUTEn01sHiWPOGCFMfp",am:"https://music.apple.com/us/artist/1834193679"},
  {n:"Notion",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/1uRVM0wBdtyEuU582EeKJM",am:"https://music.apple.com/us/artist/576443911"},
  {n:"Oklou",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/3wjk2FNnBFXMI18daSArrP",am:"https://music.apple.com/us/artist/1156489245"},
  {n:"Olivia Dean",t:"headliner",g:"Soul/Pop",sp:"https://open.spotify.com/artist/42vbMUzRMCEpnSjeIiYkAy",am:"https://music.apple.com/us/artist/1139024234"},
  {n:"Omnom",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/3PYRXP25JcbqhvNaJYcnWy",am:"https://music.apple.com/us/artist/1160083701"},
  {n:"Paloma Morphy",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/30Ph7pfibYhG9VcdOj7xZw",am:"https://music.apple.com/us/artist/1654342484"},
  {n:"Paris Paloma",t:"undercard",g:"Folk",sp:"https://open.spotify.com/artist/6i4eUAaCcJ4c3yd3VXup3w",am:"https://music.apple.com/us/artist/1530898376"},
  {n:"PartyO2",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/70KxgbZNsd9xOttXW67mh3",am:"https://music.apple.com/us/artist/1790556764"},
  {n:"Peace Control",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/3rzbheJbLKamFWE8v9fPRh",am:"https://music.apple.com/us/artist/1689855900"},
  {n:"Pearly Drops",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/2eMb96S1ZJ1YQ7FhWAzWJL",am:"https://music.apple.com/us/artist/1476836493"},
  {n:"Penelope Road",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/2BxNY82SWxJkGveOWm2oxH",am:"https://music.apple.com/us/artist/1742324131"},
  {n:"Porch Light",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/71gxkPYviG8kwEzEZGM1FH",am:"https://music.apple.com/us/artist/127092175"},
  {n:"Quadeca",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/7JlYRjHGWuwIEiYsf8oofX",am:"https://music.apple.com/us/artist/993872780"},
  {n:"Riordan",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/68rU1sdZ0HjxjEC5YnSmao",am:"https://music.apple.com/us/artist/1517575029"},
  {n:"Roz",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/0aULg7LximLNhI6lLzxcXI",am:"https://music.apple.com/us/artist/1497371365"},
  {n:"Ryman",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/1ZUNE7b5nNiN31AnJ0Smqj",am:"https://music.apple.com/us/artist/1561850927"},
  {n:"SB19",t:"undercard",g:"K-Pop",sp:"https://open.spotify.com/artist/5b7wDmMFXXSJGBZkJF7Dvl",am:"https://music.apple.com/us/artist/1439702222"},
  {n:"Sienna Spiro",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/02gSuSAWEdWa5UOvqzjX6v",am:"https://music.apple.com/us/artist/1745678083"},
  {n:"Sidepiece",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/28LaGjfBzBjjNnUvEq0kAi",am:"https://music.apple.com/us/artist/1479083020"},
  {n:"Simon Grossmann",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/6t38N9HASTn9ca0PIxfReQ",am:"https://music.apple.com/us/artist/1160960360"},
  {n:"Skye Newman",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/4UoEzpWZrFWvlGYOzTEn1M",am:"https://music.apple.com/us/artist/1799174381"},
  {n:"Slayyter",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/4obzFoKoKRHIphyHzJ35G3",am:"https://music.apple.com/us/artist/1424342162"},
  {n:"The Smashing Pumpkins",t:"headliner",g:"Rock",sp:"https://open.spotify.com/artist/40Yq4vzPs9VNUrIBG5Jr2i",am:"https://music.apple.com/us/artist/1563015"},
  {n:"Snacktime",t:"undercard",g:"Hip-Hop",sp:"https://open.spotify.com/artist/4WdKwazXyV5Hc2YtWc2IDr",am:"https://music.apple.com/us/artist/1623003380"},
  {n:"Snow Strippers",t:"major",g:"Electronic",sp:"https://open.spotify.com/artist/4FdZ0j64P9HPm4OdJoG2XP",am:"https://music.apple.com/us/artist/1597165659"},
  {n:"Sombr",t:"major",g:"Alt Pop",sp:"https://open.spotify.com/artist/4HqDPepYDIYDxOJBGBsaLN",am:"https://music.apple.com/us/artist/1589842503"},
  {n:"Spacey Jane",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/0EFisYRi20PTAEKGgMuGMz",am:"https://music.apple.com/us/artist/1274804750"},
  {n:"Stella Lefty",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/6hp2uD84OrQ3u3ukmTjLz2",am:"https://music.apple.com/us/artist/1641742186"},
  {n:"The Story So Far",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/4bJGiHMxEBiJOfNEhI8Pn0",am:"https://music.apple.com/us/artist/459805363"},
  {n:"Suki Waterhouse",t:"major",g:"Indie",sp:"https://open.spotify.com/artist/4MnA1lMeyFGHB2tpAmoVQL",am:"https://music.apple.com/us/artist/928905498"},
  {n:"Sunday (1994)",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/1vTFaCiaR50b2IXELHW52U",am:"https://music.apple.com/us/artist/1728938785"},
  {n:"Sunshine",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/0zGQRzNwUYrf3m5dinPvpo",am:"https://music.apple.com/us/artist/1522704549"},
  {n:"Surfing for Daisy",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/3zwFtNNRxR23FVS8jueGK9",am:"https://music.apple.com/us/artist/1689160758"},
  {n:"Tate McRae",t:"headliner",g:"Pop",sp:"https://open.spotify.com/artist/45dkTj5sMRSjrmBSBeiHym",am:"https://music.apple.com/us/artist/1234079587"},
  {n:"The Bends",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/2xBejdNon0VS3Egq8he7sb",am:"https://music.apple.com/us/artist/1781943253"},
  {n:"The Braymores",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/7CrVM33l2Pt32fCxJWGVw6",am:"https://music.apple.com/us/artist/1686649595"},
  {n:"The Creekers",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/2Ee2dvrxHJvnpWgaqC5T0i",am:"https://music.apple.com/us/artist/1653450262"},
  {n:"The XX",t:"headliner",g:"Indie",sp:"https://open.spotify.com/artist/3iOvXCl6edW5Um0fXEBRXy",am:"https://music.apple.com/us/artist/302595894"},
  {n:"Turnstile",t:"major",g:"Rock",sp:"https://open.spotify.com/artist/5yCdBqGssp7mBOTkMzEHca",am:"https://music.apple.com/us/artist/592368867"},
  {n:"Valencia Grace",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/5cb5ljWIIrvUxokdf2vl6A",am:"https://music.apple.com/us/artist/1532649578"},
  {n:"Vandelux",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/2rdSCmWgrIWA8pmwhS1T2k",am:"https://music.apple.com/us/artist/1094559354"},
  {n:"Viagra Boys",t:"major",g:"Rock",sp:"https://open.spotify.com/artist/1mYsTKHkNW0mWdSHFIixPP",am:"https://music.apple.com/us/artist/1122701527"},
  {n:"Villanelle",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/3J9QwmRJDdn9Oq1fB6mfcF",am:"https://music.apple.com/us/artist/1705416314"},
  {n:"Water From Your Eyes",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/7iBSoYwHSIkTf0b40uQRPk",am:"https://music.apple.com/us/artist/1211796145"},
  {n:"Waylon Wyatt",t:"undercard",g:"Country",sp:"https://open.spotify.com/artist/6Ff2omMMZOd8FWNqb980Ol",am:"https://music.apple.com/us/artist/1713519329"},
  {n:"Westend",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/4epc3Bd0DOBA0kDywkRAsu",am:"https://music.apple.com/us/artist/1436918291"},
  {n:"Wet Leg",t:"major",g:"Indie",sp:"https://open.spotify.com/artist/2TwOrUcYnAlIiKmVQkkoSZ",am:"https://music.apple.com/us/artist/1581761591"},
  {n:"Whatmore",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/2y4kS2ljmS41pNDNA01P2Q",am:"https://music.apple.com/us/artist/1797119133"},
  {n:"Whethan",t:"undercard",g:"Electronic",sp:"https://open.spotify.com/artist/5h2zBSSghYANfKHbqOIk2i",am:"https://music.apple.com/us/artist/1131838621"},
  {n:"Whitney Whitney",t:"undercard",g:"Pop",sp:"https://open.spotify.com/artist/2Jze5ZZUDEo9TowuCnI45R",am:"https://music.apple.com/us/artist/1392978294"},
  {n:"Will Swinton",t:"undercard",g:"Indie",sp:"https://open.spotify.com/artist/1fUcXY3KcnNvCP2dnF7XCh",am:"https://music.apple.com/us/artist/1572477037"},
  {n:"Wolf Alice",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/3bNv3VNApnVMphiqmcp55X",am:"https://music.apple.com/us/artist/581576780"},
  {n:"Worship",t:"major",g:"Rock",sp:"https://open.spotify.com/search/Worship",am:"https://music.apple.com/us/search?term=Worship"},
  {n:"Wunderhorse",t:"undercard",g:"Rock",sp:"https://open.spotify.com/artist/2tCdMzmSxhSSTaEMP5OXaS",am:"https://music.apple.com/us/artist/1499976480"},
  {n:"Yoasobi",t:"major",g:"J-Pop",sp:"https://open.spotify.com/artist/64tJ2EAv1R6UaZqc4iOCyj",am:"https://music.apple.com/us/artist/1489991790"},
  {n:"Yungblud",t:"major",g:"Rock",sp:"https://open.spotify.com/artist/1sBkRIssrMs1AbVkOJbc7a",am:"https://music.apple.com/us/artist/1225394502"},
  {n:"Zack Martino",t:"undercard",g:"EDM",sp:"https://open.spotify.com/artist/2US2mjK9hW7QGSBNpprlbu",am:"https://music.apple.com/us/artist/515904396"},
  {n:"Zara Larsson",t:"major",g:"Pop",sp:"https://open.spotify.com/artist/1Xylc3o4UrD53lo9CvFvVg",am:"https://music.apple.com/us/artist/607821740"}
];

// Shared globals used by both lineup pages
window.GS = ["All","Pop","Rock","Hip-Hop","Electronic","EDM","Indie","K-Pop","R&B","Alt Pop","Folk","Soul/Pop","J-Pop","Country","Classical","Various"];
window.TS = ["All","headliner","major","undercard"];
window.TL = {All:"All Tiers",headliner:"Headliners",major:"Major",undercard:"Undercard"};
window.GC = {"Pop":"#FF2D87","Rock":"#FF6B35","Hip-Hop":"#A855F7","Electronic":"#06D6A0","EDM":"#00E5FF","Indie":"#FFD166","K-Pop":"#FF69B4","R&B":"#C084FC","Alt Pop":"#F472B6","Folk":"#A3E635","Soul/Pop":"#FB923C","J-Pop":"#F43F5E","Country":"#FBBF24","Classical":"#94A3B8","Various":"#888"};
window.h2r = function(h){return parseInt(h.slice(1,3),16)+","+parseInt(h.slice(3,5),16)+","+parseInt(h.slice(5,7),16)};
