// Generates supabase/seed.sql from artists.js — the existing single source of
// truth for the static site. Build-time CLI script (same category as build.js,
// which also logs progress to stdout), not shipped app code.
//
// Usage: node scripts/gen-seed.mjs
//
// Source: 2026-07-09_lolla-accounts-migration-plan.md, Phase 1

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const require = createRequire(import.meta.url);

// artists.js is a browser global script (window.ARTISTS) with a CommonJS
// footer guard (`if (typeof module !== 'undefined') module.exports = ...`).
// Same load pattern as the repo's own `npm run` validation command.
global.window = {};
const artistsPath = path.join(ROOT, 'artists.js');
require(artistsPath);
const ARTISTS = global.window.ARTISTS;

if (!Array.isArray(ARTISTS) || ARTISTS.length === 0) {
  throw new Error(`Failed to load window.ARTISTS from ${artistsPath}`);
}

const FESTIVAL_SLUG = 'lollapalooza-2026';
const FESTIVAL_ID_PLACEHOLDER = "(select id from festivals where slug = 'lollapalooza-2026')";

const VALID_TIERS = new Set(['headliner', 'major', 'undercard']);

function sqlQuote(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function slugify(name) {
  return name
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '') // strip accents so slugs stay ASCII/URL-safe
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const seenSlugs = new Map(); // slug -> count, to disambiguate collisions deterministically
function uniqueSlug(name) {
  const base = slugify(name);
  const count = seenSlugs.get(base) ?? 0;
  seenSlugs.set(base, count + 1);
  return count === 0 ? base : `${base}-${count + 1}`;
}

const lines = [];
lines.push('-- Generated by scripts/gen-seed.mjs from artists.js — do not hand-edit.');
lines.push('-- Re-run the generator instead: node scripts/gen-seed.mjs');
lines.push('');
lines.push('-- festivals');
lines.push(
  `insert into festivals (slug, name, year, location, start_date, end_date) values ` +
    `(${sqlQuote(FESTIVAL_SLUG)}, ${sqlQuote('Lollapalooza')}, 2026, ${sqlQuote('Grant Park, Chicago, IL')}, ` +
    `${sqlQuote('2026-07-30')}, ${sqlQuote('2026-08-02')});`
);
lines.push('');
lines.push('-- artists (172 rows expected)');

let errorCount = 0;
for (const a of ARTISTS) {
  if (!VALID_TIERS.has(a.t)) {
    console.warn(`WARNING: "${a.n}" has unexpected tier "${a.t}" — check the artists_tier_check constraint before applying`);
    errorCount++;
  }
  const slug = uniqueSlug(a.n);
  lines.push(
    `insert into artists (festival_id, slug, name, tier, day, popularity, description, spotify_url, apple_url, youtube_url) values (` +
      `${FESTIVAL_ID_PLACEHOLDER}, ${sqlQuote(slug)}, ${sqlQuote(a.n)}, ${sqlQuote(a.t)}, ${a.d}, ${a.p ?? 'null'}, ` +
      `${sqlQuote(a.desc)}, ${sqlQuote(a.sp)}, ${sqlQuote(a.am)}, ${sqlQuote(a.yt)});`
  );
}

lines.push('');
lines.push('-- artist_genres (primary genre only — Phase 2 genre-audit.mjs adds secondary genres + citations)');
// Re-run slug assignment in the same iteration order used for the artists
// insert block above, so each artist is paired with the identical slug.
seenSlugs.clear();
for (const a of ARTISTS) {
  const slug = uniqueSlug(a.n);
  lines.push(
    `insert into artist_genres (artist_id, genre, is_primary, source) values (` +
      `(select id from artists where slug = ${sqlQuote(slug)} and festival_id = ${FESTIVAL_ID_PLACEHOLDER}), ` +
      `${sqlQuote(a.g)}, true, ${sqlQuote('artists.js (pre-audit)')});`
  );
}

writeFileSync(path.join(ROOT, 'supabase', 'seed.sql'), lines.join('\n') + '\n', 'utf8');

console.log(`Wrote supabase/seed.sql: ${ARTISTS.length} artists, 1 festival, ${ARTISTS.length} primary genre rows.`);
if (errorCount > 0) {
  console.warn(`${errorCount} artist(s) had unexpected tier values — review before applying the migration.`);
}
